import { Award, Crown, Medal, Star, Trophy, Zap } from 'lucide-react';
import { Badge, Card, LinkButton } from '@it-sum/ui';
import { DemoRoleGate } from '@/components/demo-role-gate';

const rewards = [
  { title: 'First steps', titleAr: 'الخطوات الأولى', detail: 'Complete your first quiz', detailAr: 'أكمل أول اختبار لك', icon: Star, earned: true },
  { title: 'Focused learner', titleAr: 'طالب متّزن', detail: 'Keep a 3-day learning streak', detailAr: 'حافظ على سلسلة تعلم لثلاثة أيام', icon: Zap, earned: true },
  { title: 'Top contributor', titleAr: 'مساهم متميز', detail: 'Reach the top 10 leaderboard', detailAr: 'ادخل قائمة أفضل 10 طلاب', icon: Crown, earned: false },
];

export default async function StudentRewardsPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const ar = locale === 'ar';
  return <DemoRoleGate requiredRole="student"><main className="mx-auto w-full max-w-7xl px-4 py-7 sm:px-6 lg:px-8" dir={ar ? 'rtl' : 'ltr'}><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><Badge tone="reward"><Trophy className="me-2 size-4" />{ar ? 'إنجازاتك' : 'Your achievements'}</Badge><h1 className="mt-3 text-headline-large text-on-background">{ar ? 'كل تقدم يستحق الاحتفال' : 'Every step deserves recognition'}</h1><p className="mt-2 text-body-large text-on-surface-variant">{ar ? 'اجمع النقاط وافتح شارات جديدة عبر التعلم والاختبارات.' : 'Collect points and unlock badges through learning and quizzes.'}</p></div><Card variant="filled" className="flex items-center gap-3 px-5 py-3"><Trophy className="size-5 text-reward" /><span className="tabular text-title-medium text-on-surface">185 {ar ? 'نقطة' : 'points'}</span></Card></div><div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_20rem]"><div className="grid gap-4 md:grid-cols-3">{rewards.map(({ title, titleAr, detail, detailAr, icon: Icon, earned }) => <Card key={title} variant={earned ? 'elevated' : 'outlined'} className={`flex h-full flex-col p-5 ${earned ? '' : 'opacity-75'}`}><div className={`grid size-12 place-items-center rounded-2xl ${earned ? 'bg-reward-container text-on-reward-container' : 'bg-surface-container text-on-surface-variant'}`}><Icon className="size-6" /></div><div className="mt-5 flex items-center justify-between gap-2"><h2 className="text-title-medium text-on-surface">{ar ? titleAr : title}</h2><Badge tone={earned ? 'reward' : 'info'}>{earned ? (ar ? 'مفتوحة' : 'Earned') : (ar ? 'مقفلة' : 'Locked')}</Badge></div><p className="mt-3 text-body-medium text-on-surface-variant">{ar ? detailAr : detail}</p></Card>)}</div><Card variant="filled" className="h-fit p-5"><div className="flex items-center gap-3"><Medal className="size-5 text-primary" /><h2 className="text-title-medium text-on-surface">{ar ? 'الترتيب' : 'Leaderboard'}</h2></div><div className="mt-5 space-y-4"><Rank name={ar ? 'أنت' : 'You'} value="185" current /><Rank name="Mariam A." value="240" /><Rank name="Seif T." value="226" /><Rank name="Ahmed R." value="214" /></div><LinkButton href={`/${locale}/student/quizzes`} variant="reward" fullWidth className="mt-6">{ar ? 'اكسب نقاطاً' : 'Earn more points'}</LinkButton></Card></div></main></DemoRoleGate>;
}
function Rank({ name, value, current = false }: { name: string; value: string; current?: boolean }) { return <div className={`flex items-center justify-between gap-3 rounded-xl px-3 py-2 ${current ? 'bg-primary-container text-on-primary-container' : 'bg-surface'}`}><span className="flex items-center gap-2 text-body-small"><span className="grid size-7 place-items-center rounded-full bg-surface-container text-label-small"><Award className="size-3.5" /></span>{name}</span><strong className="tabular text-body-small">{value}</strong></div>; }
