import { Activity, FileUp, FolderSync, Gauge, GraduationCap, ShieldCheck, UsersRound } from 'lucide-react';
import { Badge, Card, LinkButton, ProgressBar } from '@it-sum/ui';
import { DemoRoleGate } from '@/components/demo-role-gate';

export default async function AdminDemoPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const ar = locale === 'ar';
  return <DemoRoleGate requiredRole="admin"><main className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-8" dir={ar ? 'rtl' : 'ltr'}>
    <div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><Badge tone="primary">{ar ? 'وضع العرض التجريبي' : 'Demo mode'}</Badge><h1 className="mt-3 text-3xl font-semibold text-on-background">{ar ? 'لوحة تحكم المشرف' : 'Administrator dashboard'}</h1><p className="mt-2 text-on-surface-variant">{ar ? 'استعرض إدارة المحتوى والطلاب والمزامنة دون أسرار خادم.' : 'Explore content, students and synchronization controls without server secrets.'}</p></div><LinkButton href={`/${locale}/app`} variant="tonal">{ar ? 'لوحة الطالب' : 'Student dashboard'}</LinkButton></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={<GraduationCap className="size-5" />} label={ar ? 'الطلاب النشطون' : 'Active students'} value="248" /><Metric icon={<FileUp className="size-5" />} label={ar ? 'الموارد المنشورة' : 'Published resources'} value="223" /><Metric icon={<Gauge className="size-5" />} label={ar ? 'متوسط الإكمال' : 'Average completion'} value="68%" /><Metric icon={<Activity className="size-5" />} label={ar ? 'محاولات اليوم' : 'Attempts today'} value="34" /></div>
    <div className="mt-8 grid gap-5 lg:grid-cols-[1.4fr_1fr]"><Card className="p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-lg font-semibold text-on-surface">{ar ? 'صحة المحتوى والمزامنة' : 'Content and sync health'}</h2><p className="mt-1 text-sm text-on-surface-variant">{ar ? 'بيانات تجريبية مبنية على شجرة Google Drive الفعلية.' : 'Demo data based on the real Google Drive tree.'}</p></div><FolderSync className="size-6 text-primary" /></div><div className="mt-6 space-y-5"><HealthRow label={ar ? 'مزامنة المجلدات' : 'Folder synchronization'} value="100" /><HealthRow label={ar ? 'بيانات PDF المفهرسة' : 'PDF metadata indexed'} value="92" /><HealthRow label={ar ? 'جودة النص المستخرج' : 'Extracted text quality'} value="76" /></div><div className="mt-6 flex flex-wrap gap-3"><LinkButton href={`/${locale}/resources`} variant="filled">{ar ? 'فتح المكتبة' : 'Open library'}</LinkButton><LinkButton href={`/${locale}/departments`} variant="tonal">{ar ? 'هيكل الأقسام' : 'Academic structure'}</LinkButton></div></Card><Card className="p-6"><div className="flex items-center gap-3"><UsersRound className="size-6 text-primary" /><h2 className="text-lg font-semibold text-on-surface">{ar ? 'إدارة المستخدمين' : 'User management'}</h2></div><div className="mt-5 space-y-3 text-sm"><div className="flex items-center justify-between rounded-[15px] bg-surface-container p-3"><span>{ar ? 'طلبات اعتماد معلقة' : 'Pending approvals'}</span><Badge tone="warning" numeric>12</Badge></div><div className="flex items-center justify-between rounded-[15px] bg-surface-container p-3"><span>{ar ? 'مشرفو المحتوى' : 'Content admins'}</span><Badge tone="primary" numeric>8</Badge></div><div className="flex items-center justify-between rounded-[15px] bg-surface-container p-3"><span>{ar ? 'بلاغات مفتوحة' : 'Open reports'}</span><Badge tone="warning" numeric>3</Badge></div></div><div className="mt-6 flex items-center gap-2 text-sm text-success"><ShieldCheck className="size-4" />{ar ? 'عزل الجامعات مفعّل في وضع الإنتاج' : 'University isolation is enabled in production mode'}</div></Card></div>
  </main></DemoRoleGate>;
}

function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <Card className="flex items-center gap-3 p-4"><div className="grid size-10 place-items-center rounded-full bg-primary-container text-on-primary-container">{icon}</div><div><div className="text-xs text-on-surface-variant">{label}</div><div className="text-xl font-semibold text-on-surface">{value}</div></div></Card>; }
function HealthRow({ label, value }: { label: string; value: string }) { return <div><div className="mb-2 flex justify-between text-sm"><span className="text-on-surface-variant">{label}</span><strong className="text-on-surface">{value}%</strong></div><ProgressBar value={Number(value)} label={label} /></div>; }
