import { Activity, CheckCircle2, CloudCog, FileText, FolderOpen, RefreshCw, ShieldCheck, UsersRound } from 'lucide-react';
import { Badge, Card, LinkButton, ProgressBar } from '@it-sum/ui';
import { DemoRoleGate } from './demo-role-gate';

type AdminSection = 'users' | 'content' | 'quizzes' | 'sync';

const COPY = {
  users: { en: ['User management', 'Review approvals, roles and student activity.'], ar: ['إدارة المستخدمين', 'راجع طلبات الاعتماد والأدوار ونشاط الطلاب.'] },
  content: { en: ['Content library', 'Organize summaries, lectures and media from one workspace.'], ar: ['مكتبة المحتوى', 'نظّم الملخصات والمحاضرات والوسائط من مساحة واحدة.'] },
  quizzes: { en: ['Quiz operations', 'Publish questions, review attempts and protect answer keys.'], ar: ['عمليات الاختبارات', 'انشر الأسئلة وراجع المحاولات واحمِ مفاتيح الإجابات.'] },
  sync: { en: ['Drive synchronization', 'Monitor Google Drive metadata and ingestion health.'], ar: ['مزامنة Drive', 'راقب بيانات Google Drive وصحة إدخال المحتوى.'] },
} as const;

export function AdminSectionPage({ locale, section }: { locale: string; section: AdminSection }) {
  const ar = locale === 'ar';
  const [title, description] = ar ? COPY[section].ar : COPY[section].en;
  const Icon = section === 'users' ? UsersRound : section === 'content' ? FolderOpen : section === 'quizzes' ? ShieldCheck : CloudCog;
  return <DemoRoleGate requiredRole="admin"><main className="mx-auto w-full max-w-6xl px-4 py-7 sm:px-6 lg:px-8" dir={ar ? 'rtl' : 'ltr'}><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><Badge tone="primary"><Icon className="me-2 size-4" />{ar ? 'مركز الإدارة' : 'Admin center'}</Badge><h1 className="mt-3 text-headline-large text-on-background">{title}</h1><p className="mt-2 max-w-2xl text-body-large text-on-surface-variant">{description}</p></div><LinkButton href={`/${locale}/admin`} variant="tonal">{ar ? 'عودة إلى النظرة العامة' : 'Back to overview'}</LinkButton></div><div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_19rem]"><div className="space-y-5"><SectionContent section={section} ar={ar} locale={locale} /></div><aside className="space-y-4"><Card variant="elevated" className="overflow-hidden"><div className="bg-primary p-5 text-on-primary"><p className="text-label-medium text-on-primary/80">{ar ? 'الحيوية الآن' : 'Vital now'}</p><p className="mt-4 text-display-small">{section === 'users' ? '248' : section === 'content' ? '223' : section === 'quizzes' ? '34' : '100%'}</p><p className="mt-1 text-body-small text-on-primary/80">{section === 'users' ? (ar ? 'طالباً نشطاً' : 'active students') : section === 'content' ? (ar ? 'مورداً منشوراً' : 'published resources') : section === 'quizzes' ? (ar ? 'محاولة اليوم' : 'attempts today') : (ar ? 'مزامنة ناجحة' : 'sync health')}</p></div><div className="space-y-4 p-5"><Vital label={ar ? 'معدل النجاح' : 'Success rate'} value={section === 'quizzes' ? '82%' : '94%'} /><Vital label={ar ? 'آخر تحديث' : 'Last update'} value={ar ? 'منذ 4 دقائق' : '4 min ago'} /><Vital label={ar ? 'التنبيهات' : 'Alerts'} value={section === 'sync' ? '2' : '3'} /></div></Card><Card variant="filled" className="p-5"><div className="flex items-center gap-2"><Activity className="size-5 text-primary" /><h2 className="text-title-medium text-on-surface">{ar ? 'حالة التشغيل' : 'Operations status'}</h2></div><p className="mt-3 text-body-small text-on-surface-variant">{ar ? 'لا توجد أعطال حرجة. راجع التنبيهات عند الحاجة.' : 'No critical issues. Review alerts when needed.'}</p><ProgressBar value={section === 'sync' ? 100 : 86} label={ar ? 'الصحة العامة' : 'Overall health'} /></Card></aside></div></main></DemoRoleGate>;
}

function SectionContent({ section, ar, locale }: { section: AdminSection; ar: boolean; locale: string }) {
  if (section === 'users') return <Card variant="elevated" className="p-5"><Header icon={<UsersRound className="size-5" />} title={ar ? 'طلبات الاعتماد' : 'Approval queue'} /><div className="mt-5 space-y-3">{[['Ahmed R.', 'student@students.ctu.edu.eg', '12 min'], ['Mariam A.', 'mariam@students.ctu.edu.eg', '36 min'], ['Seif T.', 'seif@students.ctu.edu.eg', '1 hr']].map(([name, email, time]) => <div key={email} className="flex flex-wrap items-center justify-between gap-3 rounded-[15px] border border-outline-variant/60 p-4"><div className="flex min-w-0 items-center gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-full bg-primary-container text-on-primary-container"><UsersRound className="size-4" /></div><div className="min-w-0"><p className="truncate text-title-small text-on-surface">{name}</p><p className="truncate text-body-small text-on-surface-variant">{email}</p></div></div><div className="flex items-center gap-2"><span className="text-body-small text-on-surface-variant">{time}</span><Badge tone="warning">{ar ? 'معلق' : 'Pending'}</Badge></div></div>)}</div></Card>;
  if (section === 'content') return <Card variant="elevated" className="p-5"><Header icon={<FolderOpen className="size-5" />} title={ar ? 'المحتوى المنشور' : 'Published content'} /><div className="mt-5 grid gap-3 sm:grid-cols-2">{([['PDF summaries', '223', '92%'], ['Video lessons', '35', '76%'], ['Folders', '48', '100%'], ['Needs review', '8', '40%']] as const).map(([label, count, value]) => <div key={label} className="rounded-[15px] border border-outline-variant/60 p-4"><div className="flex items-center justify-between"><span className="text-body-small text-on-surface-variant">{ar && label === 'PDF summaries' ? 'ملخصات PDF' : ar && label === 'Video lessons' ? 'دروس فيديو' : ar && label === 'Folders' ? 'مجلدات' : ar ? 'تحتاج مراجعة' : label}</span><strong className="tabular text-title-medium text-on-surface">{count}</strong></div><ProgressBar value={Number(value.replace('%', ''))} label={String(label)} /></div>)}</div><LinkButton href={`/${locale}/resources`} variant="filled" className="mt-5" endIcon={<FileText className="size-4" />}>{ar ? 'فتح المكتبة العامة' : 'Open public library'}</LinkButton></Card>;
  if (section === 'quizzes') return <Card variant="elevated" className="p-5"><Header icon={<ShieldCheck className="size-5" />} title={ar ? 'الاختبارات المنشورة' : 'Published quizzes'} /><div className="mt-5 space-y-3">{[['اختبار الباب الأول — بايثون', '10 questions', 'Published'], ['أساسيات أمن الشبكات', '8 questions', 'Draft'], ['مراجعة الفيزياء', '12 questions', 'Scheduled']].map(([title, meta, status]) => <div key={title} className="flex flex-wrap items-center justify-between gap-3 rounded-[15px] border border-outline-variant/60 p-4"><div><p className="text-title-small text-on-surface">{ar && title === 'Published' ? 'منشور' : title}</p><p className="mt-1 text-body-small text-on-surface-variant">{meta}</p></div><Badge tone={status === 'Published' ? 'primary' : 'info'}>{ar ? status === 'Published' ? 'منشور' : status === 'Draft' ? 'مسودة' : 'مجدول' : status}</Badge></div>)}</div><LinkButton href={`/${locale}/student/quizzes`} variant="tonal" className="mt-5">{ar ? 'معاينة مركز الاختبارات' : 'Preview quiz center'}</LinkButton></Card>;
  return <Card variant="elevated" className="p-5"><Header icon={<CloudCog className="size-5" />} title={ar ? 'مزامنة Google Drive' : 'Google Drive sync'} /><div className="mt-5 rounded-[15px] bg-primary-container p-5 text-on-primary-container"><div className="flex items-center gap-3"><CheckCircle2 className="size-5" /><div><p className="text-title-medium">{ar ? 'المزامنة الأخيرة ناجحة' : 'Last sync succeeded'}</p><p className="mt-1 text-body-small opacity-80">{ar ? '403 ملفاً — منذ 4 دقائق' : '403 files — 4 minutes ago'}</p></div></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Vital label={ar ? 'ملفات جديدة' : 'New files'} value="12" /><Vital label={ar ? 'تغييرات' : 'Changes'} value="28" /><Vital label={ar ? 'تعارضات' : 'Conflicts'} value="0" /></div><LinkButton href={`/${locale}/admin`} variant="filled" className="mt-5" endIcon={<RefreshCw className="size-4" />}>{ar ? 'بدء مزامنة تجريبية' : 'Run demo sync'}</LinkButton></Card>;
}
function Header({ icon, title }: { icon: React.ReactNode; title: string }) { return <div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-[15px] bg-primary-container text-on-primary-container">{icon}</div><h2 className="text-title-large text-on-surface">{title}</h2></div>; }
function Vital({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-3"><span className="text-body-small text-on-surface-variant">{label}</span><strong className="tabular text-title-small text-on-surface">{value}</strong></div>; }
