import { ArrowUpRight, BrainCircuit, CheckCircle2, Clock3, Trophy } from 'lucide-react';
import { Badge, Card, LinkButton } from '@it-sum/ui';
import { DemoRoleGate } from '@/components/demo-role-gate';

const quizzes = [
  { title: 'اختبار الباب الأول — بايثون', titleEn: 'Chapter 1 — Python basics', meta: '10 questions · 10 points', status: 'Ready', statusAr: 'جاهز', color: 'reward' as const, href: '/ar/app/quiz/00000000-0000-4000-8000-000000000600' },
  { title: 'أساسيات أمن الشبكات', titleEn: 'Network security fundamentals', meta: '8 questions · 8 points', status: 'New', statusAr: 'جديد', color: 'primary' as const, href: '/ar/app/quiz/00000000-0000-4000-8000-000000000601' },
  { title: 'مراجعة الفيزياء — منتصف الفصل', titleEn: 'Physics midterm review', meta: '12 questions · 12 points', status: 'Locked', statusAr: 'قريباً', color: 'info' as const, href: '/ar/student/quizzes' },
];

export default async function StudentQuizzesPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const ar = locale === 'ar';
  return <DemoRoleGate requiredRole="student"><main className="mx-auto w-full max-w-7xl px-4 py-7 sm:px-6 lg:px-8" dir={ar ? 'rtl' : 'ltr'}><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><Badge tone="reward"><BrainCircuit className="me-2 size-4" />{ar ? 'تدريب ومكافآت' : 'Practice and rewards'}</Badge><h1 className="mt-3 text-headline-large text-on-background">{ar ? 'مركز الاختبارات' : 'Quiz center'}</h1><p className="mt-2 text-body-large text-on-surface-variant">{ar ? 'اختبر فهمك، اجمع النقاط، وشاهد تقدمك مع كل محاولة.' : 'Test your understanding, collect points and see your progress after every attempt.'}</p></div><Card variant="filled" className="flex items-center gap-3 px-4 py-3"><Trophy className="size-5 text-reward" /><span className="text-body-small text-on-surface-variant">185 {ar ? 'نقطة متاحة' : 'points available'}</span></Card></div><div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_18rem]"><div className="grid gap-4 md:grid-cols-2">{quizzes.map((quiz) => <Card key={quiz.title} variant="elevated" className="flex h-full flex-col p-5"><div className="flex items-start justify-between gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-primary-container text-on-primary-container"><BrainCircuit className="size-5" /></div><Badge tone={quiz.color}>{ar ? quiz.statusAr : quiz.status}</Badge></div><h2 className="mt-5 text-title-large text-on-surface">{ar ? quiz.title : quiz.titleEn}</h2><p className="mt-2 text-body-medium text-on-surface-variant">{quiz.meta}</p><div className="mt-5 flex items-center gap-4 text-body-small text-on-surface-variant"><span className="flex items-center gap-1.5"><Clock3 className="size-4" />10 min</span><span className="flex items-center gap-1.5"><CheckCircle2 className="size-4" />Instant score</span></div><div className="mt-auto pt-6"><LinkButton href={quiz.href.replace('/ar/', `/${locale}/`)} variant={quiz.status === 'Locked' ? 'outlined' : 'filled'} fullWidth endIcon={<ArrowUpRight className="size-4" />}>{quiz.status === 'Locked' ? (ar ? 'عرض قريباً' : 'Coming soon') : (ar ? 'ابدأ الاختبار' : 'Start quiz')}</LinkButton></div></Card>)}</div><Card variant="filled" className="h-fit p-5"><div className="flex items-center gap-3"><Trophy className="size-5 text-reward" /><h2 className="text-title-medium text-on-surface">{ar ? 'سجلّك' : 'Your record'}</h2></div><div className="mt-5 space-y-4"><Record label={ar ? 'اختبارات مكتملة' : 'Completed quizzes'} value="7" /><Record label={ar ? 'متوسط النتيجة' : 'Average score'} value="82%" /><Record label={ar ? 'أفضل سلسلة' : 'Best streak'} value="4" /></div><LinkButton href={`/${locale}/student/rewards`} variant="tonal" fullWidth className="mt-6">{ar ? 'شاهد مكافآتك' : 'View rewards'}</LinkButton></Card></div></main></DemoRoleGate>;
}
function Record({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-3 border-b border-outline-variant/50 pb-3 last:border-0 last:pb-0"><span className="text-body-small text-on-surface-variant">{label}</span><strong className="tabular text-title-medium text-on-surface">{value}</strong></div>; }
