import { BarChart3, CalendarDays, CheckCircle2, Flame, Target, TrendingUp } from 'lucide-react';
import { Badge, Card, CardBody, CardHeader, CardTitle, ProgressBar } from '@it-sum/ui';
import { DemoRoleGate } from '@/components/demo-role-gate';

export default async function StudentProgressPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const ar = locale === 'ar';
  const courses = ar ? [['Python Programming', 'البرمجة بلغة بايثون', 72], ['Network Security', 'أمن الشبكات', 54], ['Physics', 'الفيزياء', 38]] : [['Python Programming', 'Python Programming', 72], ['Network Security', 'Network Security', 54], ['Physics', 'Physics', 38]];
  return <DemoRoleGate requiredRole="student"><main className="mx-auto w-full max-w-7xl px-4 py-7 sm:px-6 lg:px-8" dir={ar ? 'rtl' : 'ltr'}><div className="mb-7"><Badge tone="primary"><BarChart3 className="me-2 size-4" />{ar ? 'تقدمك الدراسي' : 'Your learning progress'}</Badge><h1 className="mt-3 text-headline-large text-on-background">{ar ? 'أنت تتحرك للأمام' : 'You are moving forward'}</h1><p className="mt-2 text-body-large text-on-surface-variant">{ar ? 'تتبع عاداتك ومعدلات الإكمال وحدد هدفك القادم بوضوح.' : 'Track your habits, completion rates and choose your next clear goal.'}</p></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><Metric icon={<TrendingUp className="size-5" />} value="68%" label={ar ? 'متوسط الإكمال' : 'Average completion'} /><Metric icon={<CalendarDays className="size-5" />} value="18" label={ar ? 'يوماً نشطاً' : 'Active days'} /><Metric icon={<CheckCircle2 className="size-5" />} value="12" label={ar ? 'موارد مكتملة' : 'Completed resources'} /><Metric icon={<Flame className="size-5" />} value="4" label={ar ? 'سلسلة الأيام' : 'Day streak'} /></div><div className="mt-6 grid gap-5 lg:grid-cols-[minmax(0,1fr)_20rem]"><Card variant="elevated"><CardHeader><CardTitle>{ar ? 'التقدم حسب المادة' : 'Progress by course'}</CardTitle><p className="text-body-small text-on-surface-variant">{ar ? 'آخر تحديث منذ دقائق' : 'Updated a few minutes ago'}</p></CardHeader><CardBody className="space-y-6">{courses.map(([key, label, value]) => <div key={key as string}><div className="mb-2 flex items-center justify-between gap-3"><span className="text-title-small text-on-surface">{label}</span><strong className="tabular text-body-small text-primary">{value}%</strong></div><ProgressBar value={Number(value)} label={String(label)} /></div>)}</CardBody></Card><Card variant="filled" className="h-fit p-5"><div className="flex items-center gap-3"><Target className="size-5 text-primary" /><h2 className="text-title-medium text-on-surface">{ar ? 'هدف الأسبوع' : 'Weekly goal'}</h2></div><p className="mt-4 text-body-large text-on-surface">{ar ? 'أكمل 3 جلسات تعلم' : 'Complete 3 study sessions'}</p><div className="mt-4"><ProgressBar value={66} label={ar ? 'تقدم الهدف الأسبوعي' : 'Weekly goal progress'} /></div><p className="mt-2 text-body-small text-on-surface-variant">{ar ? 'جلستان من أصل 3' : '2 of 3 sessions'}</p></Card></div></main></DemoRoleGate>;
}
function Metric({ icon, value, label }: { icon: React.ReactNode; value: string; label: string }) { return <Card variant="filled" className="p-4"><div className="grid size-10 place-items-center rounded-full bg-primary-container text-on-primary-container">{icon}</div><p className="mt-4 text-headline-small text-on-surface">{value}</p><p className="mt-1 text-body-small text-on-surface-variant">{label}</p></Card>; }
